# Generated by Django 5.0.1 on 2024-01-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="contact_message",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact_name",
            field=models.CharField(max_length=255),
        ),
    ]
