# Generated by Django 5.0.1 on 2024-01-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_contact_contact_message_alter_contact_contact_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_name", models.CharField(max_length=255)),
                ("reg_email", models.EmailField(max_length=255)),
                ("reg_num", models.CharField(max_length=255)),
                ("reg_uname", models.CharField(max_length=255)),
                ("reg_pswrd", models.CharField(max_length=255)),
            ],
        ),
    ]
