# Generated by Django 5.0.1 on 2024-01-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="p_image",
            field=models.FileField(upload_to="products"),
        ),
    ]
