# Generated by Django 5.0.1 on 2024-01-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_alter_product_p_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cp_name", models.CharField(max_length=255)),
                ("cp_price", models.CharField(max_length=255)),
                ("cp_image", models.FileField(upload_to="")),
                ("cp_qty", models.IntegerField()),
                ("cp_amount", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="p_price",
            field=models.FloatField(max_length=255),
        ),
    ]
