# Generated by Django 5.0.1 on 2024-01-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_cart_alter_product_p_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cp_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="p_price",
            field=models.FloatField(),
        ),
    ]
