# Generated by Django 5.0.1 on 2024-02-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_cart_cp_price_alter_product_p_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odr_name', models.CharField(max_length=255)),
                ('odr_price', models.FloatField()),
                ('odr_image', models.FileField(upload_to='')),
                ('odr_qty', models.IntegerField()),
                ('odr_amount', models.FloatField()),
            ],
        ),
    ]
