# Generated by Django 5.0.1 on 2024-02-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_cart_cp_user_order_odr_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="odr_status",
            field=models.IntegerField(null=True),
        ),
    ]
