# Generated by Django 5.0.1 on 2024-02-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_order_odr_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="odr_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="odr_billname",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="odr_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="odr_phone",
            field=models.IntegerField(null=True),
        ),
    ]
