# Generated by Django 5.0.1 on 2024-02-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0013_adminlogin"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminlogin",
            name="ad_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
