# Generated by Django 5.0.1 on 2024-03-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0017_rename_category_product_p_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("w_name", models.CharField(max_length=255)),
                ("w_price", models.FloatField()),
                ("w_stock", models.CharField(max_length=255)),
            ],
        ),
    ]
