# Generated by Django 5.0.1 on 2024-03-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0019_wishlist_w_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="p_description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
