# Generated by Django 5.0.1 on 2024-03-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0021_product_p_disprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="cp_pid",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
