# Generated by Django 5.0.1 on 2024-03-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0022_cart_cp_pid"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="cp_disprice",
            field=models.FloatField(null=True),
        ),
    ]
