# Generated by Django 5.0.1 on 2024-03-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0023_cart_cp_disprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="odr_disprice",
            field=models.FloatField(null=True),
        ),
    ]
